version: "3.9"

services:
  db_auth:
    container_name: db_auth
    image: postgres:17-alpine
    env_file:
      - ./auth-service/.env
    volumes:
      - db_auth_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_network

  db_market:
    container_name: db_market
    image: postgres:17-alpine
    env_file:
      - ./market-service/.env
    volumes:
      - db_market_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend_network

  auth-service:
    container_name: auth_service
    platform: linux/amd64
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    env_file:
      - ./auth-service/.env
    ports:
      - "8080:8080"
    depends_on:
      - db_auth
    networks:
      - backend_network

  notification-service:
    container_name: notification_service
    platform: linux/amd64
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    env_file:
      - ./notification-service/.env
    ports:
      - "50051:50051"
    depends_on:
      - db_auth
      - redis
    networks:
      - backend_network

  market-service:
    container_name: market_service
    platform: linux/amd64
    build:
      context: ./market-service
      dockerfile: Dockerfile
    env_file:
      - ./market-service/.env
    ports:
      - "8081:8080"
    depends_on:
      - db_market
      - auth-service
    networks:
      - backend_network

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
    name: backend_network

volumes:
  db_auth_data:
    name: db_auth_data
  db_market_data:
    name: db_market_data

