// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/math_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VolatilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Returns       []float64              `protobuf:"fixed64,1,rep,packed,name=returns,proto3" json:"returns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolatilityRequest) Reset() {
	*x = VolatilityRequest{}
	mi := &file_api_proto_math_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolatilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolatilityRequest) ProtoMessage() {}

func (x *VolatilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_math_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolatilityRequest.ProtoReflect.Descriptor instead.
func (*VolatilityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_math_service_proto_rawDescGZIP(), []int{0}
}

func (x *VolatilityRequest) GetReturns() []float64 {
	if x != nil {
		return x.Returns
	}
	return nil
}

type VolatilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volatility    float64                `protobuf:"fixed64,1,opt,name=volatility,proto3" json:"volatility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolatilityResponse) Reset() {
	*x = VolatilityResponse{}
	mi := &file_api_proto_math_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolatilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolatilityResponse) ProtoMessage() {}

func (x *VolatilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_math_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolatilityResponse.ProtoReflect.Descriptor instead.
func (*VolatilityResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_math_service_proto_rawDescGZIP(), []int{1}
}

func (x *VolatilityResponse) GetVolatility() float64 {
	if x != nil {
		return x.Volatility
	}
	return 0
}

var File_api_proto_math_service_proto protoreflect.FileDescriptor

const file_api_proto_math_service_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/math_service.proto\x12\vmathservice\"-\n" +
	"\x11VolatilityRequest\x12\x18\n" +
	"\areturns\x18\x01 \x03(\x01R\areturns\"4\n" +
	"\x12VolatilityResponse\x12\x1e\n" +
	"\n" +
	"volatility\x18\x01 \x01(\x01R\n" +
	"volatility2g\n" +
	"\vMathService\x12X\n" +
	"\x13CalculateVolatility\x12\x1e.mathservice.VolatilityRequest\x1a\x1f.mathservice.VolatilityResponse\"\x00B6Z4gitverse.ru/volatex/backend/market-service/api/protob\x06proto3"

var (
	file_api_proto_math_service_proto_rawDescOnce sync.Once
	file_api_proto_math_service_proto_rawDescData []byte
)

func file_api_proto_math_service_proto_rawDescGZIP() []byte {
	file_api_proto_math_service_proto_rawDescOnce.Do(func() {
		file_api_proto_math_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_math_service_proto_rawDesc), len(file_api_proto_math_service_proto_rawDesc)))
	})
	return file_api_proto_math_service_proto_rawDescData
}

var file_api_proto_math_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_math_service_proto_goTypes = []any{
	(*VolatilityRequest)(nil),  // 0: mathservice.VolatilityRequest
	(*VolatilityResponse)(nil), // 1: mathservice.VolatilityResponse
}
var file_api_proto_math_service_proto_depIdxs = []int32{
	0, // 0: mathservice.MathService.CalculateVolatility:input_type -> mathservice.VolatilityRequest
	1, // 1: mathservice.MathService.CalculateVolatility:output_type -> mathservice.VolatilityResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_math_service_proto_init() }
func file_api_proto_math_service_proto_init() {
	if File_api_proto_math_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_math_service_proto_rawDesc), len(file_api_proto_math_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_math_service_proto_goTypes,
		DependencyIndexes: file_api_proto_math_service_proto_depIdxs,
		MessageInfos:      file_api_proto_math_service_proto_msgTypes,
	}.Build()
	File_api_proto_math_service_proto = out.File
	file_api_proto_math_service_proto_goTypes = nil
	file_api_proto_math_service_proto_depIdxs = nil
}
