definitions:
  request.Register:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: securepassword123
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  response.Error:
    properties:
      error:
        example: message
        type: string
    type: object
  response.User:
    properties:
      email:
        example: user@example.com
        type: string
      id:
        example: 1
        type: integer
    type: object
info:
  contact: {}
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      operationId: register
      parameters:
      - description: User registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Register'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Register
      tags:
      - auth
swagger: "2.0"
